### ISSUE TITLE
Proposal: Delete intlTelInput

### ISSUE THREAD

**Issue by ianrandmckenzie** [nxexdev/constantiam#10]
This JS library is used for validating phone numbers, a site like this doesn't need to process phone numbers or load this JS/CSS

https://github.com/jackocnr/intl-tel-input

**Comment by nxexdev** [comment]
Sounds good.
Will remove once I confirm the site is up and running.

**Comment by ianrandmckenzie** [comment]
I'm testing locally as I go, I can delete if you want.
