### ISSUE TITLE
Github Pages either broken, or down.

### ISSUE THREAD

**Issue by nxexdev** [nxexdev/constantiam#11]
Not entirely sure about this.

**Comment by ianrandmckenzie** [comment]
Most likely a DNS config issue. Either that or your DNS is extremely slow to propagate. Who is your provider?

**Comment by nxexdev** [comment]
> Most likely a DNS config issue. Either that or your DNS is extremely slow to propagate. Who is your provider?

Google Domains
The domain is working fine, it just errors to the github page.

**Comment by ianrandmckenzie** [comment]
I've seen the error many times from my own usage of GitHub pages. It is a DNS or SSL issue 99% of the time. Is there a Google SSL config that may be conflicting with GitHub's?

**Comment by nxexdev** [comment]
> I've seen the error many times from my own usage of GitHub pages. It is a DNS or SSL issue 99% of the time. Is there a Google SSL config that may be conflicting with GitHub's?

Highly unlikely, I checked everything. I setup a whole separate repository to check and that one wont even work.

**Comment by ianrandmckenzie** [comment]
https://www.githubstatus.com/

**Comment by nxexdev** [comment]
Back up, republished site. 
My sleeping schedule is screwed so
here I am.
